version: "3.9"

services:
  websocket_server:
    image: python:3.11-slim
    container_name: hexxy4-websocket-server
    working_dir: /app
    volumes:
      - ./websocketServer.py:/app/websocketServer.py
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "8001:8001"
    command: sh -c "pip install --no-cache-dir -r requirements.txt && python3 websocketServer.py"
    restart: unless-stopped
